SET TERM ^ ;

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1
      FROM RDB$RELATION_FIELDS
     WHERE TRIM(RDB$RELATION_NAME) = 'PRODUTO'
       AND TRIM(RDB$FIELD_NAME) = 'ESTOQUE'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE PRODUTO ADD ESTOQUE DECIMAL(15,4) DEFAULT 0 NOT NULL';
END
^

SET TERM ; ^
