-- ==============================
-- DROP OBJECTS (Se existirem)
-- ==============================

SET TERM ^ ;

EXECUTE BLOCK
AS
BEGIN
  IF (EXISTS(SELECT 1 FROM RDB$TRIGGERS WHERE TRIM(RDB$TRIGGER_NAME) = 'TRG_ITENS_PEDIDO_BI')) THEN
    EXECUTE STATEMENT 'DROP TRIGGER TRG_ITENS_PEDIDO_BI';
  IF (EXISTS(SELECT 1 FROM RDB$TRIGGERS WHERE TRIM(RDB$TRIGGER_NAME) = 'TRG_PEDIDO_BI')) THEN
    EXECUTE STATEMENT 'DROP TRIGGER TRG_PEDIDO_BI';
  IF (EXISTS(SELECT 1 FROM RDB$TRIGGERS WHERE TRIM(RDB$TRIGGER_NAME) = 'TRG_PRODUTO_BI')) THEN
    EXECUTE STATEMENT 'DROP TRIGGER TRG_PRODUTO_BI';
  IF (EXISTS(SELECT 1 FROM RDB$TRIGGERS WHERE TRIM(RDB$TRIGGER_NAME) = 'TRG_CLIENTE_BI')) THEN
    EXECUTE STATEMENT 'DROP TRIGGER TRG_CLIENTE_BI';
  IF (EXISTS(SELECT 1 FROM RDB$TRIGGERS WHERE TRIM(RDB$TRIGGER_NAME) = 'TGR_CLIENTE_BI')) THEN
    EXECUTE STATEMENT 'DROP TRIGGER TGR_CLIENTE_BI';

  IF (EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE TRIM(RDB$RELATION_NAME) = 'ITENS_PEDIDO')) THEN
    EXECUTE STATEMENT 'DROP TABLE ITENS_PEDIDO';
  IF (EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE TRIM(RDB$RELATION_NAME) = 'PEDIDO')) THEN
    EXECUTE STATEMENT 'DROP TABLE PEDIDO';
  IF (EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE TRIM(RDB$RELATION_NAME) = 'PRODUTO')) THEN
    EXECUTE STATEMENT 'DROP TABLE PRODUTO';
  IF (EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE TRIM(RDB$RELATION_NAME) = 'CLIENTE')) THEN
    EXECUTE STATEMENT 'DROP TABLE CLIENTE';

  IF (EXISTS(SELECT 1 FROM RDB$GENERATORS WHERE TRIM(RDB$GENERATOR_NAME) = 'GEN_CLIENTE_ID')) THEN
    EXECUTE STATEMENT 'DROP GENERATOR GEN_CLIENTE_ID';
  IF (EXISTS(SELECT 1 FROM RDB$GENERATORS WHERE TRIM(RDB$GENERATOR_NAME) = 'GEN_PRODUTO_ID')) THEN
    EXECUTE STATEMENT 'DROP GENERATOR GEN_PRODUTO_ID';
  IF (EXISTS(SELECT 1 FROM RDB$GENERATORS WHERE TRIM(RDB$GENERATOR_NAME) = 'GEN_PEDIDO_ID')) THEN
    EXECUTE STATEMENT 'DROP GENERATOR GEN_PEDIDO_ID';
END
^

SET TERM ; ^

-- ==============================
-- CREATE GENERATORS
-- ==============================

CREATE GENERATOR GEN_CLIENTE_ID;
CREATE GENERATOR GEN_PRODUTO_ID;
CREATE GENERATOR GEN_PEDIDO_ID;

-- ==============================
-- TABELA CLIENTE
-- ==============================

CREATE TABLE CLIENTE (
	CODIGO INTEGER NOT NULL PRIMARY KEY,
	NOME VARCHAR(100),
	CEP VARCHAR(8),
	LOGRADOURO VARCHAR(100),
	COMPLEMENTO VARCHAR(50),
	BAIRRO VARCHAR(50),
	CIDADE VARCHAR(50),
	UF CHAR(2),
	CODIGO_IBGE VARCHAR(10)
);

-- Trigger para CLIENTE
SET TERM ^ ;

CREATE TRIGGER TRG_CLIENTE_BI FOR CLIENTE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
    NEW.CODIGO = GEN_ID(GEN_CLIENTE_ID, 1);
END
^

SET TERM ; ^

-- ==============================
-- TABELA PRODUTO
-- ==============================

CREATE TABLE PRODUTO (
	CODIGO INTEGER NOT NULL PRIMARY KEY,
	DESCRICAO VARCHAR(100),
	VALOR_UNITARIO DECIMAL(15,2),
	ESTOQUE DECIMAL(15,4) DEFAULT 0 NOT NULL
);

-- Trigger para PRODUTO
SET TERM ^ ;

CREATE TRIGGER TRG_PRODUTO_BI FOR PRODUTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
    NEW.CODIGO = GEN_ID(GEN_PRODUTO_ID, 1);
END
^

SET TERM ; ^

-- ==============================
-- TABELA PEDIDO
-- ==============================

CREATE TABLE PEDIDO (
	CODIGO INTEGER NOT NULL PRIMARY KEY,
	REFERENCIA VARCHAR(50),
	NUMERO_PEDIDO VARCHAR(20) NOT NULL,
	DATA_EMISSAO DATE,
	CODIGO_CLIENTE INTEGER,
	TIPO_OPERACAO VARCHAR(10), -- Entrada/Saida
	TOTAL_PEDIDO DECIMAL(15,2),
	FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO),
	CONSTRAINT UNQ_PEDIDO_NUMERO UNIQUE (NUMERO_PEDIDO)
);

-- Trigger para PEDIDO
SET TERM ^ ;

CREATE TRIGGER TRG_PEDIDO_BI FOR PEDIDO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
    NEW.CODIGO = GEN_ID(GEN_PEDIDO_ID, 1);
END
^

SET TERM ; ^

-- ==============================
-- TABELA ITENS_PEDIDO
-- ==============================

CREATE TABLE ITENS_PEDIDO (
	CODIGO INTEGER NOT NULL,
	CODIGO_PEDIDO INTEGER NOT NULL,
	CODIGO_PRODUTO INTEGER,
	QUANTIDADE DECIMAL(15,4),
	VALOR_UNITARIO DECIMAL(15,2),
	TOTAL_ITEM DECIMAL(15,2),
	PRIMARY KEY (CODIGO_PEDIDO, CODIGO),
	FOREIGN KEY (CODIGO_PEDIDO) REFERENCES PEDIDO(CODIGO),
	FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTO(CODIGO)
);

-- Trigger para ITENS_PEDIDO
SET TERM ^ ;

CREATE TRIGGER TRG_ITENS_PEDIDO_BI FOR ITENS_PEDIDO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF ((NEW.CODIGO IS NULL) OR (NEW.CODIGO = 0)) THEN
  BEGIN
    UPDATE PEDIDO
       SET CODIGO = CODIGO
     WHERE CODIGO = NEW.CODIGO_PEDIDO;

    SELECT COALESCE(MAX(CODIGO), 0) + 1
      FROM ITENS_PEDIDO
     WHERE CODIGO_PEDIDO = NEW.CODIGO_PEDIDO
      INTO NEW.CODIGO;
  END
END
^

SET TERM ; ^
